"""Add password to person

Revision ID: 8706ad1b78aa
Revises: 
Create Date: 2023-03-10 06:23:31.079343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8706ad1b78aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('firstname', sa.String(length=30), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('quarter', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person'))
    )
    op.create_table('deliver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['person.id'], name=op.f('fk_deliver_id_person')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliver'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deliver')
    op.drop_table('person')
    # ### end Alembic commands ###
